oauth2:
  user:
    github:
      client-id: 6c34d9a6903231c5a301
      client-secret: 비밀키
      redirect-uri: http://localhost:8080/redirect/oauth
    google:
      client-id: 54767115914-gcla0mork6h3156h4qcutjerm0mdf4fu.apps.googleusercontent.com
      client-secret: 비밀키
      redirect-uri: http://localhost:8080/redirect/oauth
    naver:
      client-id: sCfhQHgPVQFFf8RTGjVe
      client-secret: 비밀키
      redirect-uri: http://localhost:8080/redirect/oauth
  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me

